apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: iris
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
        - name: iris
          image: intersystemsdc/iris-community:2020.4.0.524.0-zpm
          imagePullPolicy: Always
          ports:
          - containerPort: 51773
          - containerPort: 52773
