apiVersion: v1
kind: Service
metadata:
  name: iris
spec:
  type: LoadBalancer
  ports:
  - name: iris-server
    port: 51773
    protocol: TCP
    targetPort: 51773
  - name: iris-web
    port: 52773
    protocol: TCP
    targetPort: 52773
  - name: iris-agent
    port: 2188
    protocol: TCP
    targetPort: 2188
  selector:
    app: iris
